export const GameActions = {
  RESET: "RESET",
  FLIP_SLAB: "FLIP_SLAB",
  MATCH_SLAB: "MATCH_SLAB",
  NEXT_ROUND: "NEXT_ROUND",
  DECREMENT_TIME: "DECREMENT_TIME",
  GAME_OVER: "GAME_OVER",
  RESET_FLIPPED: "RESET_FLIPPED",
};
